name: Python Fuzzing

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hypothesis
    - name: Run fuzzing tests
      run: python fuzz.py

